instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from models.user import User
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from flask_login import current_user
from instagram_web.util.helpers import upload_file_to_s3
from app import app


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():

    username = request.form['username'] 
    email = request.form['email']
    password = request.form['password']
    hashed_password = generate_password_hash(password)
    user = User(username= username, email= email, password=hashed_password)

    if user.save():
      flash('User has successfully been created')
      return render_template('sessions/new.html', username = user.username)
    else:
      return render_template('users/new.html', name=request.form['username'])


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.get_or_none(User.username == username)
    if user:
        return render_template('users/show.html', user = user)
    else:
        flash('no such user found')
        return redirect(url_for('home'))


@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
def edit(id):
    user = User.get_or_none(User.id == id)
    return render_template('users/edit.html', user = user)



@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):
            params = request.form
            
            user.username = params.get('username')
            user.email = params.get('email')

            # password = params.get('password')

            if user.save():
                flash('Details have been updated succesfully!')
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('Something went wrong')
                return redirect(url_for('users.show', username = user.username))


@users_blueprint.route('/<id>/updatepassword', methods=['POST'])
def updatepassword(id):
    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):
            params = request.form
 
            password = params.get('password')
            print(password)
            hashed_password = generate_password_hash(password)
            user.password = hashed_password
            
            if  user.save():
                flash('Password has been succesfully updated!')
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('Something went wrong')
                return redirect(url_for('users.show', username = user.username))


@users_blueprint.route('/<id>/upload', methods=['POST'])
def upload(id):

    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):

    
            if 'user_file' not in request.files:
                return "No user_file key in request.files"
            
            file = request.files['user_file']

            print(file.content_type)

            if file.filename == "":
                return "Please select a file"
            
            file.filename = secure_filename(file.filename)
            image_path   	  = upload_file_to_s3(file, app.config["S3_BUCKET"])


            print(user.username, user.id, user.email, user.profile_image_path)
            user.profile_image_path = image_path
            print(user.username, user.id, user.email, user.profile_image_path)

            if user.save():
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('image upload failed')
                return redirect(url_for('users.show', username = user.username))
        
        else:
            flash('Hey, change your own profile!')
            return redirect(url_for('users.show', username = user.username))
    
    else:
        flash('Username not found')
        return redirect(url_for('home'))




# @users_blueprint.route('<id>/profile', methods=['GET'])
# def profile():
#     if session.get('user_id'):
#         # use the sessions's user_id value ste via login

#         user = User.get_or_none(User.id == session['user_id'])
#         if user:
#             username = user.username
#         else:
#             username = None
#         return render_template('users/profile.html', username = username)
#     else:
#         return redirect(url_for('sessions.new'))

instagram_web/blueprints/users/templates/users/edit.html
{% extends "_layout.html" %}

{% block title %}
{% endblock %}


{% block content %}
<h1>Users#Edit</h1>

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <form action="{{url_for('users.update', id = user.id)}}" method='POST'>

                <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>

                <div class="form-group">
                    <label for="username">New Username</label>
                    <input type="text" class="form-control" id="username" name='username' value='{{user.username}}'
                        placeholder="Username" />
                </div>

                <div class="form-group">
                    <label for="email">New Email address</label>
                    <input type="email" class="form-control" id="email" name='email' value='{{user.email}}'
                        placeholder="Email" />
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small>
                </div>

                <button type="submit" class="btn btn-primary mb-2">Edit details</button>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <form action="{{url_for('users.updatepassword', id = user.id)}}" method='POST'>

                <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>  

                <div class="form-group">
                    <label for="password">New Password (If you don't want to change your password, leave it
                        empty)</label>
                    <input type="password" class="form-control" id="password" placeholder="Password" name='password'
                        title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
                        pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*?[0-9])(?=.*?[!@#$%^&*+`~=?\|<>/]).{8,}" required>
                    <small id="passwordhelp" class="form-text text-muted">Must contain at least one number and one
                        uppercase and lowercase letter, and at least 8 or more characters.</small>
                </div>


                <button type="submit" class="btn btn-primary mb-2">Change password</button>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <form action="{{url_for('users.upload', id = user.id)}}" method="POST" enctype="multipart/form-data">

                <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>

                <div class="form-group">
                    <label for="user_file">Upload Your File</label>
                    <input type="file" class="form-control-file"  name="user_file">
                    <small id="passwordhelp" class="form-text text-muted">Here you must specify which files can be uploaded. have to check if this is arrange with client side and server side authentication </small>
                </div>
                
                <button type="submit" class="btn btn-primary mb-2">Upload</button>
            </form>
        </div>
    </div>
</div>

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
{{ message }}
{% endfor %}
{% endif %}
{% endwith %}

{% endblock %}

instagram_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %}

{% block title %}
{% endblock %}


{% block content %}
<h1>Users#new</h1>

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-4">
            <form action="{{url_for('users.create')}}" method='POST'>
                <input type="hidden" name='csrf_token' value= '{{ csrf_token() }}'>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name='username' value='{{username}}' placeholder= "Username" />
                </div>
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name='email' value='{{email}}' placeholder="Email" />
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="Password" name='password' title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*?[0-9])(?=.*?[!@#$%^&*+`~=?\|<>/]).{8,}" required>
                    <small id="passwordhelp" class="form-text text-muted">Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters.</small>
                </div>


                <button type="submit" class="btn btn-primary mb-2">Create account</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

instagram_web/blueprints/users/templates/users/profile.html
{% extends "_layout.html" %}

{% block title %}
{% endblock %}


{% block content %}
<h1>Users#Profile</h1>

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
{{ message }}
{% endfor %}
{% endif %}
{% endwith %}

{% endblock %}

instagram_web/blueprints/users/templates/users/show.html
{% extends "_layout.html" %}

{% block title %}
{% endblock %}


{% block content %}

<h1>profile page</h1>



{% if current_user.id == user.id%}

<a href="{{url_for('users.edit', id = current_user.id)}}" >edit profile</a>

<img src='{{user.profile_image_path}}' class='userimageprofilepage'/>

{%endif%}

<div class='container'>
    {% for image in user.images %}
        <img src="{{image.image_url}}" width='300' />
    {% endfor %}
</div>

{% endblock %}