instagram_web/blueprints/images/views.py
from flask import Blueprint, render_template, redirect, request, flash
from flask.helpers import url_for
from werkzeug.utils import secure_filename
from models.image import Image
from instagram_web.util.helpers import upload_file_to_s3
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import app
from flask_login import current_user
from models.image import Image
from models.user import User

images_blueprint = Blueprint('images',
                            __name__,
                            template_folder='templates')


@images_blueprint.route('/new')
def new():
    return render_template('images/new.html')

@images_blueprint.route('/show', methods=["GET"])
def show():
    images = Image.select()
    users = User.select()
    
    for image in images:
        print(image.image_url)

    if images:
        return render_template('images/show.html', images = images, users= users)
    else:
        flash('Sorry, now pictures to show')
        return redirect(url_for('home'))

@images_blueprint.route('/', methods=["POST"])
def create():
    if 'user_file' not in request.files:
        return 'no file found'

    file = request.files['user_file']

    file.filename = secure_filename(file.filename)

    #save image to S3 and get path
    image_path = upload_file_to_s3(file, app.config["S3_BUCKET"])

    print(image_path)

    caption = request.form['caption'] 
    hashtags = request.form['hashtags']
    print(hashtags)

    #save image object to database

    image = Image(image_url=image_path, user_id=current_user.id, image_caption=caption, image_hashtags=hashtags)

    print('!!!', image.image_hashtags)
    if image.save():
        flash('Image succesfully saved')
        return redirect(url_for('users.show', username= current_user.username))
    else:
        flash('Upload failed')
        return render_template('images/new.html')
    return render_template('images/new.html')

instagram_web/blueprints/images/templates/images/new.html
<h1> upload image</h1>

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div>
            <form action="{{url_for('images.create')}}" method="POST" enctype="multipart/form-data">

                <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>

                <div class="form-group">
                    <label for="user_file">Upload Your File</label>
                    <input type="file" class="form-control-file" name="user_file">
                    <small id="passwordhelp" class="form-text text-muted">Here you must specify which files can be
                        uploaded. have to check if this is arrange with client side and server side authentication
                    </small>

                <div class="form-group">
                    <label for="caption">Caption</label>
                    <input type="text" class="form-control" id="caption" name='caption' placeholder="Place here some caption text for your photo." />
                </div>

                <div class="form-group">
                    <label for="hashtags">Hashtags</label>
                    <input type="text" class="form-control" id="hashtags" name='hashtags' placeholder="#nextafamous" />
                </div>

                <button type="submit" class="btn btn-primary mb-2">Upload</button>
            </form>
        </div>
    </div>
</div>

instagram_web/blueprints/images/templates/images/show.html
{% extends "_layout.html" %}

{% block title %}
{% endblock %}


{% block content %}
{% for image in images %}
<section class="hero">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3">

                <div class="cardbox shadow-lg bg-white">

                    <div class="cardbox-heading">
                        <!-- START dropdown-->
                        <div class="dropdown float-right">
                            <button class="btn btn-flat btn-flat-icon" type="button" data-toggle="dropdown"
                                aria-expanded="false">
                                <em class="fa fa-ellipsis-h"></em>
                            </button>
                            <div class="dropdown-menu dropdown-scale dropdown-menu-right" role="menu"
                                style="position: absolute; transform: translate3d(-136px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="#">Hide post</a>
                                <a class="dropdown-item" href="#">Stop following</a>
                                <a class="dropdown-item" href="#">Report</a>
                            </div>
                        </div>
                        <!--/ dropdown -->
                        <div class="media m-0">
                            <div class="d-flex mr-3">
                                <a href=""><img class="img-fluid rounded-circle"
                                        src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/4.jpg"
                                        alt="User"></a>
                            </div>
                            <div class="media-body">
                                <p class="m-0">John Doe</p>
                                <small><span><i class="icon ion-md-pin"></i> Nairobi, Kenya</span></small>
                                <small><span><i class="icon ion-md-time"></i> 10 hours ago</span></small>
                            </div>
                        </div>
                        <!--/ media -->
                    </div>
                    <!--/ cardbox-heading -->

                    <div class="cardbox-item">
                        <img class="img-fluid"
                            src="{{image.image_url}}" alt="Image">
                    </div>
                    <!--/ cardbox-item -->
                    <div class="cardbox-base">
                        <ul class="float-right">
                            <li><a><i class="fa fa-comments"></i></a></li>
                            <li><a><em class="mr-5">12</em></a></li>
                            <li><a><i class="fa fa-share-alt"></i></a></li>
                            <li><a><em class="mr-3">03</em></a></li>
                        </ul>
                        <p>{{image.image_caption}}</p>
                        <p class="font-weight-light">{{image.image_hashtags}}</p>
                        <ul>
                            <li><a><i class="fa fa-thumbs-up"></i></a></li>
                            <li><a href="#"><img
                                        src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/3.jpeg"
                                        class="img-fluid rounded-circle" alt="User"></a></li>
                            <li><a href="#"><img
                                        src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/1.jpg"
                                        class="img-fluid rounded-circle" alt="User"></a></li>
                            <li><a href="#"><img
                                        src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/5.jpg"
                                        class="img-fluid rounded-circle" alt="User"></a></li>
                            <li><a href="#"><img
                                        src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/2.jpg"
                                        class="img-fluid rounded-circle" alt="User"></a></li>
                            <li><a><span>242 Likes</span></a></li>
                        </ul>
                    </div>
                    <!--/ cardbox-base -->
                    <div class="cardbox-comments">
                        <span class="comment-avatar float-left">
                            <a href=""><img class="rounded-circle"
                                    src='{{current_user.profile_image_path}}'
                                    alt="..."></a>
                        </span>
                        <div class="search">
                            <input placeholder="Write a comment" type="text">
                            <button><i class="fa fa-camera"></i></button>
                        </div>
                        <!--/. Search -->
                    </div>
                    <!--/ cardbox-like -->

                </div>
                <!--/ cardbox -->

            </div>
            <!--/ col-lg-6 -->
            <div class="col-lg-3">
                
            </div>
            <!--/ col-lg-3 -->

        </div>
        <!--/ row -->
    </div>
    <!--/ container -->
</section>
{% endfor %}

<!-- {% for image in images %}
    <img src="{{image.image_url}}" width='300' />
{% endfor %}

{% for user in users %}
    <li>{{user.username}}</li>
{% endfor %} -->

{% endblock %}