instagram_web/__init__.py
from app import app
from flask import render_template
from instagram_web.blueprints.users.views import users_blueprint
from instagram_web.blueprints.sessions.views import sessions_blueprint
from instagram_web.blueprints.images.views import images_blueprint
from flask_assets import Environment, Bundle
from .util.assets import bundles

assets = Environment(app)
assets.register(bundles)

app.register_blueprint(users_blueprint, url_prefix="/users")
app.register_blueprint(sessions_blueprint, url_prefix='/sessions')
app.register_blueprint(images_blueprint, url_prefix='/images')


@app.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500


@app.route("/")
def home():
    return render_template('home.html')

instagram_web/blueprints/images/views.py
from flask import Blueprint, render_template, redirect, request, flash
from flask.helpers import url_for
from werkzeug.utils import secure_filename
from models.image import Image
from instagram_web.util.helpers import upload_file_to_s3
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import app
from flask_login import current_user
from models.image import Image
from models.user import User

images_blueprint = Blueprint('images',
                            __name__,
                            template_folder='templates')


@images_blueprint.route('/new')
def new():
    return render_template('images/new.html')

@images_blueprint.route('/show', methods=["GET"])
def show():
    images = Image.select()
    users = User.select()
    
    for image in images:
        print(image.image_url)

    if images:
        return render_template('images/show.html', images = images, users= users)
    else:
        flash('Sorry, now pictures to show')
        return redirect(url_for('home'))

@images_blueprint.route('/', methods=["POST"])
def create():
    if 'user_file' not in request.files:
        return 'no file found'

    file = request.files['user_file']

    file.filename = secure_filename(file.filename)

    #save image to S3 and get path
    image_path = upload_file_to_s3(file, app.config["S3_BUCKET"])

    print(image_path)

    caption = request.form['caption'] 
    hashtags = request.form['hashtags']
    print(hashtags)

    #save image object to database

    image = Image(image_url=image_path, user_id=current_user.id, image_caption=caption, image_hashtags=hashtags)

    print('!!!', image.image_hashtags)
    if image.save():
        flash('Image succesfully saved')
        return redirect(url_for('users.show', username= current_user.username))
    else:
        flash('Upload failed')
        return render_template('images/new.html')
    return render_template('images/new.html')

instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from models.user import User
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from flask_login import current_user
from instagram_web.util.helpers import upload_file_to_s3
from app import app


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/', methods=['POST'])
def create():

    username = request.form['username'] 
    email = request.form['email']
    password = request.form['password']
    hashed_password = generate_password_hash(password)
    user = User(username= username, email= email, password=hashed_password)

    if user.save():
      flash('User has successfully been created')
      return render_template('sessions/new.html', username = user.username)
    else:
      return render_template('users/new.html', name=request.form['username'])


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.get_or_none(User.username == username)
    if user:
        return render_template('users/show.html', user = user)
    else:
        flash('no such user found')
        return redirect(url_for('home'))


@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"


@users_blueprint.route('/<id>/edit', methods=['GET'])
def edit(id):
    user = User.get_or_none(User.id == id)
    return render_template('users/edit.html', user = user)



@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):
            params = request.form
            
            user.username = params.get('username')
            user.email = params.get('email')

            # password = params.get('password')

            if user.save():
                flash('Details have been updated succesfully!')
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('Something went wrong')
                return redirect(url_for('users.show', username = user.username))


@users_blueprint.route('/<id>/updatepassword', methods=['POST'])
def updatepassword(id):
    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):
            params = request.form
 
            password = params.get('password')
            print(password)
            hashed_password = generate_password_hash(password)
            user.password = hashed_password
            
            if  user.save():
                flash('Password has been succesfully updated!')
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('Something went wrong')
                return redirect(url_for('users.show', username = user.username))


@users_blueprint.route('/<id>/upload', methods=['POST'])
def upload(id):

    user = User.get_or_none(User.id == id)

    if user:
        if current_user.id == int(id):

    
            if 'user_file' not in request.files:
                return "No user_file key in request.files"
            
            file = request.files['user_file']

            print(file.content_type)

            if file.filename == "":
                return "Please select a file"
            
            file.filename = secure_filename(file.filename)
            image_path   	  = upload_file_to_s3(file, app.config["S3_BUCKET"])


            print(user.username, user.id, user.email, user.profile_image_path)
            user.profile_image_path = image_path
            print(user.username, user.id, user.email, user.profile_image_path)

            if user.save():
                return redirect(url_for('users.show', username = user.username))
            else:
                flash('image upload failed')
                return redirect(url_for('users.show', username = user.username))
        
        else:
            flash('Hey, change your own profile!')
            return redirect(url_for('users.show', username = user.username))
    
    else:
        flash('Username not found')
        return redirect(url_for('home'))




# @users_blueprint.route('<id>/profile', methods=['GET'])
# def profile():
#     if session.get('user_id'):
#         # use the sessions's user_id value ste via login

#         user = User.get_or_none(User.id == session['user_id'])
#         if user:
#             username = user.username
#         else:
#             username = None
#         return render_template('users/profile.html', username = username)
#     else:
#         return redirect(url_for('sessions.new'))

instagram_web/templates/_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}

    {% assets "home_js" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% block header %}
    {% endblock %}

    {{ modals() }}

    <title>
      {% block title %}
      {% endblock %}NEXTAGRAM
    </title>

  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    <footer>
      Made with &hearts; at <a target="_blank" href="https://www.nextacademy.com/?utm_source=github&utm_medium=student-challenge&utm_campaign=flask-nextagram">NEXT Academy</a>
    </footer>
  </body>
</html>

instagram_web/templates/home.html
{% extends "_layout.html" %}

{% block title %}
  Homepage

{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
  <h1>Homepage</h1>

  {% if current_user.is_authenticated %}
    <h2>Hello, welcome {{current_user.username}}, {{current_user.email}}</h2>
  {% endif%}


  {% endblock %}

instagram_web/templates/loginmodal.html
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginmodal" data-whatever="@mdo">Log in</button>

<div class="modal fade" id="loginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginmodal">Sign in</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="loginmodal">
        {{ modal_messages() }}
        <form action="{{url_for('sessions.login')}}" , method='POST'>
          <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name='username' value='{{username}}' placeholder="Username" />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" placeholder="Password" name='password'
              title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
              required>
          </div>

          <button type="submit" class="btn btn-primary mb-2">Log in</button>
        </form>
      </div>
    </div>
  </div>
</div>

instagram_web/templates/logoutbutton.html
<form action="{{url_for('sessions.logout')}}" , method='POST'>
    <input type="hidden" name='csrf_token' value='{{ csrf_token() }}'>
    <button type="submit" class="btn btn-danger m-2" name='button'>Log out</button>
</form>

instagram_web/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" id='navbar'>
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('images.show', images = images, users= users)}}">Home</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.show', username = current_user.username)}}" >Profile</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.edit', id = current_user.id)}}">Edit</a>
                </li>
                {% endif%}
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>

            </ul>
            
        </div>
        <div class="float-right">
            <div class="inline-block"></div>
            {% if current_user.is_authenticated %}
            {% include 'logoutbutton.html' %}
            </div>
            <div class="inline-block">
            {% include 'uploadpicturemodal.html' %}
            </div>
            {% else %}
            {% include 'loginmodal.html' %}
            {% endif%}
        </div>
    </div>
</nav>

instagram_web/templates/uploadpicturemodal.html
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#loginmodal" data-whatever="@mdo">Upload</button>

<div class="modal fade" id="loginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginmodal">Upload Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="loginmodal">
        {{ modal_messages() }}
      {% include 'images/new.html' %}
      </div>
    </div>
  </div>
</div>